[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:backend]
command=python /app/backend/main.py
directory=/app/backend
environment=SYNAPSE_DATA_DIR="/data",PYTHONPATH="/app/backend",SYNAPSE_BACKEND_PORT="%(ENV_SYNAPSE_BACKEND_PORT)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=1

[program:frontend]
command=node /app/frontend/server.js
directory=/app/frontend
environment=NODE_ENV="production",BACKEND_URL="http://localhost:%(ENV_SYNAPSE_BACKEND_PORT)s",PORT="%(ENV_SYNAPSE_FRONTEND_PORT)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=2
